- name: Load image
  hosts: master
  tasks:
    - name: Copy driver files
      ansible.builtin.copy:
        src: "../drivers/{{ driver }}"
        dest: .

    - name: Build image
      become: true
      ansible.builtin.shell: "docker build -t {{ ansible_ssh_host }}:30000/benches/{{ driver }} ."

    - name: Push image
      become: true
      ansible.builtin.shell: "docker push {{ ansible_ssh_host }}:30000/benches/{{ driver }}"