- name: Load image
  hosts: master
  tasks:
    - name: Tag and push to docker hub
      community.docker.docker_image:
        name: {{ image }}-bench
        repository: {{ ansible_ssh_host }}:30000/{{ image }}-bench:latest
        push: true
        source: local