- name: Master node setup
  hosts: master
  become: true
  tasks:
    - name: Install k3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -s - --disable traefik --write-kubeconfig-mode 644 --node-name master --node-external-ip {{ ansible_ssh_host }}

    - name: Create kube config dir
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: '0755'

    - name: Copy kube config
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: $HOME/.kube/config
        remote_src: true

    - name: Wait for all k3s nodes to be ready
      ansible.builtin.shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s

    - name: Get kube token
      ansible.builtin.fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: node-token
        flat: true

    - name: Install helm
      ansible.builtin.shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash