- name: Setup worker
  ansible.builtin.import_playbook: k3s-agent.yaml

- name: Worker node setup
  hosts: workers
  tasks:
    - name: Install nfs-common
      become: true
      ansible.builtin.apt:
        name: nfs-common
        state: latest