- name: Setup worker
  ansible.builtin.import_playbook: k3s-agent.yaml

- name: Worker node setup
  hosts: workers
  tasks:
    - name: Create a directory if it does not exist
      become: true
      ansible.builtin.file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Copy k3s_registry.yaml
      become: true
      ansible.builtin.copy:
        src: data/k3s_registry.yaml
        dest: /etc/rancher/k3s/registries.yaml
        mode: 'g+w'

    - name: Restart k3s-agent
      become: true
      ansible.builtin.systemd:
        state: restarted
        name: k3s-agent

    - name: Install nfs-common
      become: true
      ansible.builtin.apt:
        name: nfs-common
        state: latest