[package]
name = "benchmark-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
console = "0.15.7"
hcl-rs = "0.16.6"
home = "0.5.5"
indicatif = "0.17.7"
lazy_static = "1.4.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
regex = "1.10.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
toml = "0.8.8"
virt = "0.3.1"
whoami = "1.4.1"
