version: "3.9"
services:
  graphs:
    container_name: graphs
    restart: always
    build: ./
    depends_on:
      - benchmarks_db
    environment:
      - SELECT_LOG_ID=1
      - POSTGRES_HOST=benchmarks_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./results:/app/results
      - .:/app
    
  benchmarks_db:
    container_name: benchmarks_db
    image: postgres:16.1-alpine
    restart: unless-stopped
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=benchmarks_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      # Copy the initialization sql script and optionally exisiting data.
      - ./migrations/bin/init/db-dump.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_volume:/var/lib/postgresql/data
 