apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-import
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  nfs:
    path: /bench-storage
    server: 10.43.30.214
