- name: Graphscope helm destroy
  hosts: master
  tasks:
    - name: Remove graphscope
      kubernetes.core.helm:
        name: graphscope
        release_namespace: default
        chart_ref: graphscope/graphscope
        release_state: absent