- name: Graphscope helm setup
  hosts: master
  tasks:
    - name: Add helm repo
      kubernetes.core.helm_repository:
        name: graphscope
        repo_url: https://graphscope.oss-cn-beijing.aliyuncs.com/charts/

    - name: Copy chart values
      ansible.builtin.copy:
        src: values.yaml
        dest: $HOME/values.yaml
        mode: 'g+w'

    - name: Install graphscope
      kubernetes.core.helm:
        name: graphscope
        release_namespace: default
        chart_ref: graphscope/graphscope
        values_files:
          - values.yaml