image:
  tag: 0.26.0a20231205
engines:
  gae:
    resources:
      requests:
        cpu: 8
        memory: 8Gi
      limits:
        cpu: 8
        memory: 8Gi
  gie:
    resources:
      requests:
        cpu: 8
        memory: 8Gi
      limits:
        cpu: 8
        memory: 8Gi
  num_workers: 4
withJupyter: false
vineyard:
  resources:
    requests:
      cpu: 2
      memory: 12Gi
    limits:
      cpu: 2
      memory: 12Gi
  shared_mem: 1024Gi
coordinator:
  resources:
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2
      memory: 3Gi